### ISSUE TITLE
Docker container this works inside of for arm 64?

### ISSUE THREAD

**Issue by jpcookie** [Bertral/wrAIter#1]
I'm trying to get this to work on a Jetson nano rather than cloud deployment but I'm stuck in python module dependency gridlock. Did you test this with a certain docker container perhaps that would act as a control on the mushrooming errors I'm getting?

**Comment by FontaineRiant** [comment]
Hi!

There are complications that could happen when installing wrAIter on a different machine than mine. I upgraded my GPU and now tensorflow 1 isn't a compatible option anymore, for example.

Locally, I migrated everything to pytorch and GPT-NEO which could solve loads of compatibility issues and improves text quality. I have yet to check that launch options still work, rewrite the documentation, then publish the new branch. It should be done in the coming week.

**Comment by FontaineRiant** [comment]
The new version is on branch pytorch-gptneo and should be much easier to setup. You'll need pytorch and CUDA 11.1.
I also cleaned my venv and remade requirements.txt from scratch. Some dependencies were broken on windows but they seem to have been fixed.
