### ISSUE TITLE
Ollama support for LLM

### ISSUE THREAD

**Issue by razvanab** [Bertral/wrAIter#5]
Is there any way to use ollama for the llm?
Ollama now supports using models directly from the hugging face.

https://huggingface.co/docs/hub/ollama

**Comment by FontaineRiant** [comment]
I'm looking into what ollama does and I'm not sure what you mean. Ollama isn't an LLM, it's a user interface like wrAIter.
It could be used as a local REST API server but chatting isn't wrAIter's primary function.

However Ollama uses GGUF models if that's what you mean, and transformers supports it.
https://github.com/FontaineRiant/wrAIter/commit/816d2d58188467c4974c42b063aefdbaa94c5a14 introduces GGUF support. You'll need to specify model_gguf_file (the name of the .gguf file) in settings.json. If you encounter an "unknown model type" error, you'll have to also set model_gguf_type to "mistral" or "llama" or whatever you're using.

Transformers support for GGUF isn't complete yet, see https://huggingface.co/docs/transformers/en/gguf for the list of model types and quantizations that you can use.

**Comment by razvanab** [comment]
Yes, I misspoke. I was eager to test your app. Sorry about that.
So, is it possible to use the app with Olama already without setting the IP address for the server?

**Comment by FontaineRiant** [comment]
It's not possible to use Ollama, but you can use the same LLMs as Ollama that you can find on huggingface.
Here's an example of a settings.json file that uses [Llama 3.2 8B](https://huggingface.co/prithivMLmods/Llama-3.2-8B-GGUF-200K) for text generation in wrAIter:
```
{
    "model": "prithivMLmods/Llama-3.2-8B-GGUF-200K",
    "model_gguf_file": "Llama-3.2-8B.F16.gguf"
}
```
It will download and run the model.

**Comment by razvanab** [comment]
I see.
Thanks
